### ISSUE TITLE
Functionality request

### ISSUE THREAD

**Issue by buildpress** [manogi/october-mediathumb#1]
Hi,

For functionality reasons of this plugin is it possible to extend the features enabling multi size thumb outputs?

Separate folders (for example name is size of the thumbs) holding separate thumb sizes.

Jasper

**Comment by bastihilger** [comment]
I'm not sure if that's the direction I'm going. The thumbnails are - at the moment - created on-the-go. So I don't the see the reason for creating multiple thumbnails while only one of them is used. The way it is set up right now you can use 

```
{{ 'path/to/image.jpg'|mediathumb_resize('width', 400) }}
```

at one place and

```
 {{ 'path/to/image.jpg'|mediathumb_resize('width', 800) }}
```

at another place.

But please elaborate so I can understand your issue.

**Comment by buildpress** [comment]
Yes, that will work :-) thnx. 

Codenator81 is developping a backend API for powering a mobile app. For the variety of end user devices i wanted to have multiple image thumbnails formats.

Can i back your work somehow by sending you some coffee? Hoping the plugin remains in development.

**Comment by bastihilger** [comment]
Thanks Jasper. Did you see that the plugin is now officially [added to the October CMS plugins](http://octobercms.com/plugin/manogi-mediathumb)? 
I already made the first change, adding Amazon S3 support.
Thanks for your offer, all I'd like right now is for you to keep me posted if you have any issues ;-)

**Comment by bastihilger** [comment]
By the way, the plugin will remain in development as I will use it in all my October CMS projects.
