### ISSUE TITLE
Frond and tumbnails not working on build 385

### ISSUE THREAD

**Issue by Beaudinn** [manogi/october-mediathumb#12]
The tumbnail is multiple times created first one is in good size the other is not and that one is displayed on the page.

**Comment by bastihilger** [comment]
Could you please be more precise. What exactly did you try to do, what is the code you used... otherwise I will not be able to help.

**Comment by Beaudinn** [comment]
Hey,

I tried to create a thumbnail with you plugin on multiple locations inside my project. 
because first it works and now it doesnt i dont know what goes wrong. I've updated october several times. 

A sample of the implementation.
`product.image|mediathumb_resize('weight', 380)`

**Comment by bastihilger** [comment]
a little bit more of your code would maybe help, but "weight" ist not an option, only "height".

**Comment by bastihilger** [comment]
or "width", for example.

**Comment by Beaudinn** [comment]
Hey, I wanted to let you know that it was a mistake on my part.

I replace the **weight** with **width** 

thanks again

**Comment by bastihilger** [comment]
OK, glad it worked out.
