### ISSUE TITLE
When using S3, local URL is returned instead of S3 url?

### ISSUE THREAD

**Issue by RobbeVW** [manogi/october-mediathumb#14]
Whenever I use something like:
    `{{ post.featured_images.first().getPath() | resize(300, 200) }}`
(post.featured.images.first() returns a URL to an image stored on S3)

it will return the following directory: 
    `https://domain.tld/storage/app/uploads/public/d7b/4ad/93e/thumb__300x200_0_0_crop.jpg`

however, shouldn't it return the following S3 URL, since I'm using S3.
    `https://s3-eu-west-2.amazonaws.com/robvw-portfolio/public/589/7c4/8b1/5897c48b1748f489870465.png`

or am I missing something here?

Thanks in advance.

**Comment by bastihilger** [comment]
You are right, that is not correct - i will look into this.

**Comment by bastihilger** [comment]
This is fixed now. The fix is already included in the last update of this plugin. 
You might have to clear your application cache to see the changes.
Thanks for pointing out the error.
