### ISSUE TITLE
Broken with octobercms 1.0.407

### ISSUE THREAD

**Issue by justb81** [manogi/october-mediathumb#17]
This commit breaks the mediathumb-twig-filter https://github.com/octobercms/october/commit/5aa351f67c0f9b4d7b1b5c5cb6c2199d19164c79

**Comment by bastihilger** [comment]
Oh - thanks for notifying me. I will see if I can change the plugin accordingly.

**Comment by justb81** [comment]
i have a fix ready and a PR in a second
