### ISSUE TITLE
If I have media storage on Amazon stil this work for me?

### ISSUE THREAD

**Issue by Codenator81** [manogi/october-mediathumb#2]

**Comment by bastihilger** [comment]
The part that uses Laravel Storage should. I am not sure about the part that uses Intervention Image. I will check and post my findings here later on.

**Comment by Codenator81** [comment]
I see in your code static patch https://github.com/manogi/october-mediathumb/blob/master/Plugin.php#L135
May be it not going to work
You can make event there for extensibility

**Comment by bastihilger** [comment]
You are right. I will work the plugin over so that it works with Amazon S3 and post here when I am finished testing.

**Comment by Codenator81** [comment]
Best way just work the same as media library. Because library can manage any type of storage. I think you should take it from storage settings?

**Comment by bastihilger** [comment]
Now works with S3.

**Comment by Codenator81** [comment]
Great work!

**Comment by bastihilger** [comment]
Thanks. Did you see that the plugin is now officially [added to the October CMS plugins](http://octobercms.com/plugin/manogi-mediathumb)? Please keep my posted if you encounter any issues.

**Comment by Codenator81** [comment]
Great news!
